### Create and register user account
POST http://127.0.0.1:5001/farmflow-d2ece/us-central1/api/auth/register
Accept: : application/json
Content-Type: application/json

{
	"email": "realherrold@gmail.com",
	"blackListed": false,
	"name": "Herrold Real",
	"roles": [
		"owner",
        "admin"
	],
	"password": "lalala.1",
	"phone": "+505 89517503"
}

### Verify token
POST http://127.0.0.1:5001/farmflow-d2ece/us-central1/api/auth/verifyToken
Accept: application/json
Content-Type: application/json

{
	"token": ""
}
